package com.app;

import static com.app.FrmViewCars.carID;
import static com.app.SQLite.conn;
import static com.app.SQLite.stmt;
import static com.app.SQLite.url;
import static java.sql.DriverManager.getConnection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;

public class FrmUpdateTransaction extends javax.swing.JFrame {

    public FrmUpdateTransaction() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        if(SQLite.openDB()){
            String[][] r = SQLite.read("tblTransactionDetails1", carID);
            this.lblID.setText(r[0][0]);
            this.lblSdate.setText(r[0][1]);
            this.lblEdate.setText(r[0][2]);
            this.lblTno.setText(r[0][3]);
            
            SQLite.closeDB();
        }
        Car();
    }
    
    private void Car(){
       try{
            SQLite.conn = getConnection(SQLite.url);
            SQLite.stmt = SQLite.conn.createStatement();
            String query = "select * from tblCar";

            ResultSet rs = SQLite.stmt.executeQuery(query);
            while(rs.next()){
                String no= rs.getString("carno");
                this.cbCar.addItem(no);
            }
       }
       catch(Exception e){
           System.out.println("error: " + e.getMessage());
       }
    }
    
    private boolean checkRentalSchedule(){
        boolean valid = false;
        try {
            conn = getConnection(url);
            stmt = conn.createStatement();
            
            int id = Integer.parseInt(this.cbCar.getSelectedItem().toString());
            SimpleDateFormat dateFormat1 = new SimpleDateFormat("yyyy-MM-dd");
            String dateStart = this.lblSdate.getText();
            String dateEnd = this.lblEdate.getText();
            
            System.out.println("id = " + id);

            String query = "select * from tblTransactionDetails1 where carno='"+id+"' and '"+dateStart+"' between sdate " +
                        "and edate or carno='"+id+"' and '"+dateEnd+"' between sdate and edate or" + 
                        " carno='"+id+"' and sdate between '"+dateStart+"' and '"+dateEnd+"' or " + 
                        " carno='"+id+"' and edate between '"+dateStart+"' and '"+dateEnd+"'";

            ResultSet rss = stmt.executeQuery(query);
            
            if(rss.next()){
                System.out.println("FOUND!");
                valid = true;
            }else
                System.out.println("NOT FOUND!");
            
            
            conn.close();
        } catch (SQLException ex) {
            
        }
                
        return valid; 
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbClient = new javax.swing.JComboBox<>();
        lblID = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblSdate = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblTno = new javax.swing.JLabel();
        lblEdate = new javax.swing.JLabel();
        cbCar = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        cbClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbClientActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblID.setText("jLabel1");

        jButton1.setBackground(new java.awt.Color(0, 255, 255));
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("ID");

        jLabel3.setText("Start Date");

        jLabel4.setText("Car no");

        lblSdate.setText("jLabel1");

        jLabel5.setText("End Date");

        jLabel6.setText("Transaction No.");

        lblTno.setText("jLabel1");

        lblEdate.setText("jLabel1");

        cbCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("UPDATE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(93, 93, 93)
                        .addComponent(lblID))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(72, 72, 72)
                        .addComponent(cbCar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSdate)
                            .addComponent(lblTno)
                            .addComponent(lblEdate)))
                    .addComponent(jSeparator1)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblSdate))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblEdate))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblTno))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(checkRentalSchedule()){
            javax.swing.JOptionPane.showMessageDialog(null, "Your selected date is invalid");
        } else{
            if(SQLite.openDB()){
               try{
                   SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
                   
                   String values = "carno = '" + this.cbCar.getSelectedItem() + "'";
                   SQLite.update("tblTransactionDetails1", values, carID);

                   javax.swing.JOptionPane.showMessageDialog(null, "UPDATED!");
                   dispose();
               }
               catch(Exception e){
                   javax.swing.JOptionPane.showMessageDialog(null, e.getMessage());
               }
               SQLite.closeDB();
           }   
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbClientActionPerformed

    private void cbCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUpdateTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUpdateTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUpdateTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUpdateTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmUpdateTransaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbCar;
    private javax.swing.JComboBox<String> cbClient;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblEdate;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblSdate;
    private javax.swing.JLabel lblTno;
    // End of variables declaration//GEN-END:variables
}
